export const OBJECT_TYPES = {
  array: "[object Array]",
  object: "[object Object]",
  arguments: "[object Arguments]",
  string: "[object String]",
  function: "[object Function]",
  date: "[object Date]",
  regExp: "[object RegExp]",
  map: "[object Map]",
  set: "[object Set]",
  error: "[object Error]",
  aggregateError: "[object AggregateError]",
  domException: "[object DOMException]",
  promise: "[object Promise]",
};
